apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjoge30sCgkJImh0dHBzOi8vaW5kZXguZG9ja2VyLmlvL3YxLyI6IHt9LAoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS9hY2Nlc3MtdG9rZW4iOiB7fSwKCQkiaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvcmVmcmVzaC10b2tlbiI6IHt9Cgl9LAoJImNyZWRzU3RvcmUiOiAib3N4a2V5Y2hhaW4iLAoJImN1cnJlbnRDb250ZXh0IjogImF2aXRvIiwKCSJjbGlQbHVnaW5zRXh0cmFEaXJzIjogWwoJCSIvb3B0L2hvbWVicmV3L2xpYi9kb2NrZXIvY2xpLXBsdWdpbnMiCgldCn0=
type: kubernetes.io/dockerconfigjson
